# https://github.com/realm/SwiftLint#configuration
# https://realm.github.io/SwiftLint/rule-directory.html
# swiftlint rules

included: Sources

analyzer_rules:
  - explicit_self

opt_in_rules:
  - explicit_acl
  - explicit_top_level_acl
  - modifier_order
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self

disabled_rules:
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - duplicate_imports
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - identifier_name
  - implicit_getter
  - large_tuple
  - line_length
  - nesting
  - opening_brace
  - orphaned_doc_comment
  - private_over_fileprivate
  - todo
  - type_body_length
  - type_name
  - unavailable_condition
  - unused_closure_parameter
  - weak_delegate

trailing_comma:
  mandatory_comma: true

trailing_whitespace:
  ignores_comments: false

vertical_whitespace:
  max_empty_lines: 2

switch_case_alignment:
  indented_cases: true
